cloud:
  aws:
    s3:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region: us-east-2
      stack:
        auto: false
      public-bucket:
        name: ${S3_BUCKET}


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8081
