server:
  port: 8082

jwt:
  secret: filestorage

cloud:
  aws:
    s3:
      credentials:
        access-key: filestorage_test
        secret-key: filestorage1978
      region:
        static: us-east-1
        auto: false
      stack:
        auto: false

application:
  s3:
    url: http://localhost:9900
    bucket:
      name: filestorage-pub

spring:
  security:
    user:
       password: user

  datasource:
    url: jdbc:postgresql://localhost:5435/filestorage
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  #sql.init.mode: always  #init db from .sql script -- создает структуру
  jpa:
    properties:
      hibernate:
        format-sql: true #2
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # -- Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto:  create

    generate-ddl: true
    show-sql: true #2 -- показывает код в консоли
  defer-datasource-initialization: true #1


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB


