server:
  port: 8082

jwt:
  secret: filestorage

cloud:
  aws:
    s3:
      credentials:
        access-key: filestorage_test
        secret-key: filestorage1978
      region:
        static: us-east-1
        auto: false
      stack:
        auto: false

application:
  s3:
    url: http://localhost:9900/minio/
    bucket:
      name: filestorage-pub

spring:
  security:
    user:
        password: user12345

  datasource:
    url: jdbc:postgresql://localhost:5435/filestorage
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update
    generate-ddl: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB


